# vim: syntax=yaml


## rules for react components

extends:
 - google
 - eslint:recommended
 - plugin:react/recommended
 - plugin:flowtype/recommended

plugins:
 - flowtype

parser: babel-eslint

env:
  node: true
  browser: true
  jest: true

rules:
  # jsdoc is mandatory
  require-jsdoc: 0
  # jsx rules
  react/no-danger-with-children: 0
  react/no-string-refs: 0

