language: node_js
node_js:
  - '4'
  - '6'
  - '7'
  - '8'
sudo: false
before_script:
  - npm install -g npm
script: npm install && npm run build:webui && npm run test-travis
after_success: npm run coverage:codecov
